// actions/types.js

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GUEST_READ_SERVICES = 'GUEST_READ_SERVICES';
export const READ_SERVICES = 'READ_SERVICES';
export const READ_PROJECTS = 'READ_PROJECTS';
export const ACCEPT_PROJECT = 'ACCEPT_PROJECT';
export const REJECT_PROJECT = 'REJECT_PROJECT';